### ISSUE TITLE
Login labels overlay text if fields are prefilled

### ISSUE THREAD

**Issue by wbigger** [Born2Code-2017/CMYG#4]
If I save username and password on my browser, than navigate to the login page, the field are pre-filled. See attachment.
<img width="579" alt="screen shot 2017-11-29 at 2 48 30 pm" src="https://user-images.githubusercontent.com/3594326/33378278-95908fa4-d514-11e7-8ddf-3251077adec6.png">

**Comment by ghost** [comment]
# Issue fixed

The issue is fixed, you can pull the latest version and try it.

**Comment by wbigger** [comment]
Tested, it works now.
