### ISSUE TITLE
Dashboard doesn't display any event

### ISSUE THREAD

**Issue by wbigger** [Born2Code-2017/CMYG#5]
On the `localhost:4200/dashboard` page, no events are displayed.

![screenshot-2017-11-29 coevents](https://user-images.githubusercontent.com/3594326/33378507-4c111cb2-d515-11e7-912a-753cb2cfeea3.png)
Label is "Discover Events".

Is it correct? In this case, please add some events in this and next weeks to let people make some test. Otherwise, change the label of this issue in bug.

**Comment by ghost** [comment]
## Issue solved

As yesterday I did an http post to firebase, the for of won't work anymore due to the new key of any events in the JSON.

Already fixed and now works fine with the for in.

**Comment by wbigger** [comment]
Tested, it works.
